name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      # - name: Prettier Check
      #   run: npm run lint
      # - name: Unit tests
      #   run: npm run test
      - name: build
        run: npm run build
