# This is a basic workflow to help you get started with Actions
name: cise-server-deployment

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

jobs:
  build:
    runs-on:
      labels: edugator-frontend
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      
      - name: Build Edugator Staff Application
        run: |
          npm install
          npm run build
      
      - name: Deploy app build to cise servers
        run: |
          rm -rf /www/edugator.cise.ufl.edu/*
          cp -a -r build/* /www/edugator.cise.ufl.edu
